# Generated by Django 5.2.4 on 2025-08-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='comleted',
            field=models.BooleanField(default=False),
        ),
    ]
